### ISSUE TITLE
Not syncronizing. My Fault?

### ISSUE THREAD

**Issue by tracyleblanc** [flodaq/apimo-prorealestate-synchronizer#1]
Hello,

I'm trying to use your app to synchronize an Apimo account with WP Pro Real Estate 7 as suggested in your docs, but it has not synchronized since last night. There are listings in the Apimo account. I'm not very familiar with the Wordpress scheduler so am I missing something?

Thank you for your work on this plugin. I'm looking forward to using it.

Tracy Le Blanc

**Comment by flodaq** [comment]
Thanks for the report. The synchronization problem has been corrected.
